name: Gerar .exe Windows
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Python 32-bit
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: 'x86'

    - run: pip install pygame pyinstaller

    - run: pyinstaller --noconfirm --onefile --windowed --name "Missao_na_Escola_32bit" main.py

    - uses: actions/upload-artifact@v4
      with:
        name: Missao_na_Escola_32bit
        path: dist/Missao_na_Escola_32bit.exe
